name: Run Telegram Userbot

on:
  workflow_dispatch:
  schedule:
    - cron: "*/10 * * * *"

jobs:
  run-userbot:
    runs-on: ubuntu-latest
    timeout-minutes: 9

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm install

      - name: Run Userbot
        run: timeout 500 node userbot/index.js
        env:
          API_ID: ${{ secrets.API_ID }}
          API_HASH: ${{ secrets.API_HASH }}
          STRING_SESSION: ${{ secrets.STRING_SESSION }}
